"use client";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { createTheme, ThemeProvider } from "@mui/material/styles";

const theme = createTheme({
  palette: {
    primary: {
      main: "rgb(100, 255, 53)",
    },
  },
});

// Font files can be colocated inside of `pages`
const myFont = localFont({ src: "./Moonhouse-yE5M.woff2" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className={myFont.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
